### ISSUE TITLE
Unix paths in going into production

### ISSUE THREAD

**Issue by proddata** [crate/crate-howtos#211]
###  Documentation feedback

 
- Page title: Going into production
- Page URL: https://crate.io/docs/crate/howtos/en/latest/going-into-production.html
- Source: https://github.com/crate/crate-howtos/blob/master/docs/going-into-production.rst

---

Maybe a pit nit picky, but isn't `/srv` also a system-level directory? and shouldn't logs be kept in `/var/logs` especially if `/srv` is mounted from a separate drive (e.g. cloud deployments)? (so that logging, doesn't interfere with db performance)

``` yaml
path.conf: /srv/crate/config
path.data: /srv/crate/data
path.logs: /srv/crate/logs
path.repo: /srv/crate/snapshots
```
