### ISSUE TITLE
Missing POD_NAME EnvVar in cluster-deployment example

### ISSUE THREAD

**Issue by StWiemann** [crate/crate-howtos#264]
###  Documentation feedback

 
- Page title: Run CrateDB on Kubernetes
- Page URL: https://crate.io/docs/crate/howtos/en/latest/deployment/containers/kubernetes.html
- Source: https://github.com/crate/crate-howtos/blob/master/docs/deployment/containers/kubernetes.rst

---

If you (like me) try to launch crate in your cluster, using the provided guide and you get the Error that "Node-Name" mustn't be empty, try to add the following to the deployment yaml:

```
env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
```
This goes into the env-field, analogous to NAMESPACE. Since the arg-field uses ${POD_NAME}, it needs to be defined there.
